/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ConverMoneda;

/**
 *
 * @author oscar
 */
public class Prueba extends javax.swing.JInternalFrame {

    /**
     * Creates new form Prueba
     */
    public Prueba() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        convMonedaGrande = new javax.swing.JLabel();
        convMonedaPequenio = new javax.swing.JLabel();
        convTemperaturaPequenio = new javax.swing.JLabel();
        convTemperaturaGrande = new javax.swing.JLabel();
        convUniMedidasPequenio = new javax.swing.JLabel();
        convUniMedidasGrande = new javax.swing.JLabel();

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 20)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("¿QUÉ QUIERES HACER?");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 39, 298, 43));

        convMonedaGrande.setBackground(new java.awt.Color(0, 204, 204));
        convMonedaGrande.setFont(new java.awt.Font("Comic Sans MS", 1, 20)); // NOI18N
        convMonedaGrande.setForeground(new java.awt.Color(255, 0, 0));
        convMonedaGrande.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        convMonedaGrande.setText("Conversor de moneda");
        convMonedaGrande.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 1, true));
        convMonedaGrande.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                convMonedaGrandeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                convMonedaGrandeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                convMonedaGrandeMouseExited(evt);
            }
        });
        jPanel2.add(convMonedaGrande, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 290, 50));

        convMonedaPequenio.setBackground(new java.awt.Color(0, 204, 204));
        convMonedaPequenio.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        convMonedaPequenio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        convMonedaPequenio.setText("Conversor de moneda");
        convMonedaPequenio.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 1, true));
        convMonedaPequenio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                convMonedaPequenioMouseEntered(evt);
            }
        });
        jPanel2.add(convMonedaPequenio, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 250, 30));

        convTemperaturaPequenio.setBackground(new java.awt.Color(0, 204, 204));
        convTemperaturaPequenio.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        convTemperaturaPequenio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        convTemperaturaPequenio.setText("Conversor de temperatura");
        convTemperaturaPequenio.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 1, true));
        convTemperaturaPequenio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                convTemperaturaPequenioMouseEntered(evt);
            }
        });
        jPanel2.add(convTemperaturaPequenio, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 250, 30));

        convTemperaturaGrande.setBackground(new java.awt.Color(0, 204, 204));
        convTemperaturaGrande.setFont(new java.awt.Font("Comic Sans MS", 1, 20)); // NOI18N
        convTemperaturaGrande.setForeground(new java.awt.Color(255, 0, 0));
        convTemperaturaGrande.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        convTemperaturaGrande.setText("Conversor de temperatura");
        convTemperaturaGrande.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 1, true));
        convTemperaturaGrande.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                convTemperaturaGrandeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                convTemperaturaGrandeMouseExited(evt);
            }
        });
        jPanel2.add(convTemperaturaGrande, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 290, 50));

        convUniMedidasPequenio.setBackground(new java.awt.Color(0, 204, 204));
        convUniMedidasPequenio.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        convUniMedidasPequenio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        convUniMedidasPequenio.setText("Conversor Uni. de Medida");
        convUniMedidasPequenio.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 1, true));
        convUniMedidasPequenio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                convUniMedidasPequenioMouseEntered(evt);
            }
        });
        jPanel2.add(convUniMedidasPequenio, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 250, 30));

        convUniMedidasGrande.setBackground(new java.awt.Color(0, 204, 204));
        convUniMedidasGrande.setFont(new java.awt.Font("Comic Sans MS", 1, 20)); // NOI18N
        convUniMedidasGrande.setForeground(new java.awt.Color(255, 0, 0));
        convUniMedidasGrande.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        convUniMedidasGrande.setText("Conversor Uni. de Medida");
        convUniMedidasGrande.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 204), 1, true));
        convUniMedidasGrande.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                convUniMedidasGrandeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                convUniMedidasGrandeMouseExited(evt);
            }
        });
        jPanel2.add(convUniMedidasGrande, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 290, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 519, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 415, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void convMonedaGrandeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_convMonedaGrandeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_convMonedaGrandeMouseClicked

    private void convMonedaGrandeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_convMonedaGrandeMouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_convMonedaGrandeMouseEntered

    private void convMonedaGrandeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_convMonedaGrandeMouseExited
        // TODO add your handling code here:
        convMonedaPequenio.setVisible(true);
        convMonedaGrande.setVisible(false);
    }//GEN-LAST:event_convMonedaGrandeMouseExited

    private void convMonedaPequenioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_convMonedaPequenioMouseEntered
        // TODO add your handling code here:
        convMonedaPequenio.setVisible(false);
        convMonedaGrande.setVisible(true);
    }//GEN-LAST:event_convMonedaPequenioMouseEntered

    private void convTemperaturaPequenioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_convTemperaturaPequenioMouseEntered
        // TODO add your handling code here:
        convTemperaturaPequenio.setVisible(false);
        convTemperaturaGrande.setVisible(true);
    }//GEN-LAST:event_convTemperaturaPequenioMouseEntered

    private void convTemperaturaGrandeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_convTemperaturaGrandeMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_convTemperaturaGrandeMouseEntered

    private void convTemperaturaGrandeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_convTemperaturaGrandeMouseExited
        // TODO add your handling code here:
        convTemperaturaPequenio.setVisible(true);
        convTemperaturaGrande.setVisible(false);
    }//GEN-LAST:event_convTemperaturaGrandeMouseExited

    private void convUniMedidasPequenioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_convUniMedidasPequenioMouseEntered
        // TODO add your handling code here:
        convUniMedidasPequenio.setVisible(false);
        convUniMedidasGrande.setVisible(true);
    }//GEN-LAST:event_convUniMedidasPequenioMouseEntered

    private void convUniMedidasGrandeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_convUniMedidasGrandeMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_convUniMedidasGrandeMouseEntered

    private void convUniMedidasGrandeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_convUniMedidasGrandeMouseExited
        // TODO add your handling code here:
        convUniMedidasPequenio.setVisible(true);
        convUniMedidasGrande.setVisible(false);
    }//GEN-LAST:event_convUniMedidasGrandeMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel convMonedaGrande;
    private javax.swing.JLabel convMonedaPequenio;
    private javax.swing.JLabel convTemperaturaGrande;
    private javax.swing.JLabel convTemperaturaPequenio;
    private javax.swing.JLabel convUniMedidasGrande;
    private javax.swing.JLabel convUniMedidasPequenio;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
